### ISSUE TITLE
Reporte de práctica-Hilos

### ISSUE THREAD

**Issue by Brisa-4** [SistemasTecTlaxiaco/practica-de-hilos-Brisa-4#2]
[Reporte de práctica-Hilos.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-Brisa-4/files/6528942/Reporte.de.practica-Hilos.pdf)

**Comment by MariaC232** [comment]
Calificación: 20% 
Buen trabajo

**Comment by josealfredo79** [comment]
Bien hecho y revisado
